export const english = {
  about_this_address: 'About this address',
  back_to_place_matches: 'Back to place matches',
  back_to_search: 'Back to search',
  brush_collection: 'Brush Collection',
  brush_week: 'Brush Week',
  data_type: 'Address',
  every: 'Every',
  neighborhood: 'Neighborhood',
  no_neighborhood_name: 'No neighborhood name',
  no_city_pickup: 'No city pickup',
  no_information_available: 'No information available',
  of_next_week: 'of next week',
  of_this_week: 'of this week',
  owner: 'Owner',
  property_information: 'Property information',
  recycle_week: 'Recycle Week',
  recycling_collection: 'Recycling collection',
  report_with_the_asheville_app: 'Report with the Asheville App',
  street_maintenance: 'Street Maintenance',
  trash_collection: 'Trash Collection',
  weekdays: {
    MONDAY: 'MONDAY',
    TUESDAY: 'TUESDAY',
    WEDNESDAY: 'WEDNESDAY',
    THURSDAY: 'THURSDAY',
    FRIDAY: 'FRIDAY',
    SATURDAY: 'SATURDAY',
    SUNDAY: 'SUNDAY',
  },
  zoning: 'Zoning',
};
