export const content = {
  about_this_address: 'Sobre esta dirrecci\xF3n',
  back_to_place_matches: 'Volver a lugares',
  back_to_search: 'Volver a buscar',
  brush_collection: 'Colecci\xF3n de la broza',
  brush_week: 'Programa de broza',
  data_type: 'Dirrecci\xF3n',
  every: 'Cada',
  neighborhood: 'Barrio',
  no_neighborhood_name: 'Barrio sin nombre',
  no_city_pickup: 'no proporcionada por la ciudad de Asheville',
  no_information_available: 'No hay informaci\xF3n disponisble',
  of_next_week: 'de la pr\xF3xima semana',
  of_this_week: 'de esta semana',
  owner: 'Propietario',
  property_information: 'Detalles de la propiedad',
  recycle_week: 'Programa de reciclaje',
  recycling_collection: 'Colecci\xF3n de Reciclaje',
  report_with_the_asheville_app: 'Reportar con el Asheville App',
  street_maintenance: 'Mantenimiento de la calle',
  trash_collection: 'Recolecci\xF3n de basura',
  weekdays: {
    MONDAY: 'LUNES',
    TUESDAY: 'MARTES',
    WEDNESDAY: 'MI\xC9RCOLES',
    THURSDAY: 'JUEVES',
    FRIDAY: 'VIERNES',
    SATURDAY: 'S\xC1BADO',
    SUNDAY: 'DOMINGO',
  },
  zoning: 'Zonificaci\xF3n',
};
