version: 0.2

phases:
  install:
    commands:
      - echo "install step"
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get -y update
      - apt-get install -y yarn
      - yarn -v
      - yarn install
  build:
    commands:
      - npm run build
      - npm run deployDashboards
      - npm run deploySimplicity
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "${DASHBOARDS_DIST_ID}" --paths '/*'
      - aws cloudfront create-invalidation --distribution-id "${SIMPLICITY_DIST_ID}" --paths '/*'
      - aws cloudfront create-invalidation --distribution-id "${SIMPLICITY2_DIST_ID}" --paths '/*'