version: 0.2

phases:
  install:
    commands:
      - echo "install step"
      - npm install
  build:
    commands:
      - npm run build
      - npm run deployDashboards
      - npm run deploySimplicity
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "${DASHBOARDS_DIST_ID}" --paths '/*'
      - aws cloudfront create-invalidation --distribution-id "${SIMPLICITY_DIST_ID}" --paths '/*'
