export const testProjectData = [
 {
   "GIS_ID": "B160028",
   "MUNIS Project Number": "",
   "Project": "Land Aquisition",
   "Display Name": "Land Aquisition",
   "Location Details": "North & South Asheville",
   "Zip Code": "Citywide",
   "Category": "Bond - Parks Program",
   "COA Contact": "Roderick Simmons",
   "Phone Number": "(828) 259-5800",
   "Email Address": "RSimmons@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Parks and Rec Dept.",
   "Project Description": "Land acquisition for areas located in north and south Asheville are budgeted within the $17 million Parks & Recreation General Obligation bond package. The Asheville Parks, Recreation, Cultural Arts and Greenways Master Plan (2009) identifies a need for the City to transition to a position of leading planned development around pre-identified gaps in services for open space and parks.  ",
   "Status": "Status: Planning",
   "GO Bond Funding": "$2,000,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$2,000,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160028.png",
   "Map Tab": "Bond -  Parks",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "",
   "Need PM Fields?": "no"
 },
 {
   "GIS_ID": "B160029",
   "MUNIS Project Number": "",
   "Project": "Outdoor Court Improvements",
   "Display Name": "Outdoor Courts",
   "Location Details": "",
   "Zip Code": "Citywide",
   "Category": "Bond - Parks Program",
   "COA Contact": "Mark Halstead",
   "Phone Number": "(828) 259-5800",
   "Email Address": "mhalstead@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "Outdoor Court Improvements\nUpgrades and improvements to outdoor courts are budgeted within the $17 million Parks & Recreation General Obligation bond package.  Outdoor court projects have been prioritized focusing on underserved areas of the city. The primary goal of the project is to address maintenance backlog for our outdoor courts while building for the future, incorporating ideas and trends to enhance user experience. Durability of design and materials will be incorporated with the goal of building in long-term recreation use.\n\nPreliminary outdoor court sites include:                                                                                                                                                   Murphy-Oakley Park                                                                                                                                                                                                                                                                                                                                         Weaver  Park                                                                                                                                                                                                                                                                                                                                                  \nMontford Park \nMalvern Hills Park",
   "Status": "Status: Design",
   "GO Bond Funding": "$1,015,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,015,000",
   "Project Folder": "https://drive.google.com/drive/folders/0B7OOZhzd-WP1dHlFMVZVeWo0ZEU?usp=sharing",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160029.jpg",
   "Map Tab": "Bond - Parks",
   "Project Updates": "Selected ADC engineering. Montofrd, Weaver, Oakley, Malvern Hills are identified parks.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 18 - Summer 19",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160030",
   "MUNIS Project Number": "X1708",
   "Project": "Playground Improvements",
   "Display Name": "Playgrounds",
   "Location Details": "",
   "Zip Code": "Citywide",
   "Category": "Bond - Parks Program",
   "COA Contact": "Dee Black",
   "Phone Number": "(828) 259-5800",
   "Email Address": "dblack@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "Upgrades and improvements to playgrounds are budgeted within the $17 million Parks & Recreation General Obligation bond package. The primary goal of the project is to address maintenance backlog for playgrounds while building for the future. Playground projects have been prioritized focusing on underserved areas of the city. Each project will address the needs of diverse park users to better reflect changing neighborhoods and their long-term recreation requirements. The playgrounds will be designed to reflect their individual neighborhood setting, utilize ideas and trends from some of the best playgrounds in the country, and create unique play experience for all users. Playground upgrades may include playground equipment, rubber fall zone surface, landscaping, park shelters, shade structures, open play areas, accessible pedestrian circulation systems, and other Park & Recreation park standard furnishings.   \n\nPreliminary playground sites include:                                                                                                                                                   Lakewood Park                                                                                                                                                                                                                                                                                                                                         Magnolia Park                                                                                                                                                                                                                                                                                                                                                 West Asheville Center \nHerb Watts Park                                                                                                                                                                                                                                                                                                                                                    ",
   "Status": "Status: Design",
   "GO Bond Funding": "$1,015,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,015,000",
   "Project Folder": "https://drive.google.com/drive/folders/0B7OOZhzd-WP1WkxBTHBWRmtUZnM?usp=sharing",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160030.jpg",
   "Map Tab": "Bond - Parks",
   "Project Updates": "Schematic Designs by Surface 678",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 18 -  ",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160002",
   "MUNIS Project Number": "X1707",
   "Project": "Montford Complex Improvements",
   "Display Name": "Montford Complex",
   "Location Details": "34 Pearson Dr",
   "Zip Code": "28801",
   "Category": "Bond - Parks Program",
   "COA Contact": "Debbie Ivester",
   "Phone Number": "(828) 259-5800",
   "Email Address": "divester@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "Upgrades and improvements to the Montford Complex are budgeted within the $17 million Parks & Recreation General Obligation bond package. Proposed investments are aligned with the recommendations outlined in the previously compleded park facility site plan.  THe phase 1 priorities identified would include a playground, parking improvements, outdoor classroom/picnic areas, edible gardens, accessible pedestrian systems, shade structures, lighting, and other Park & Recreation standard park furnishings.",
   "Status": "Status: Design",
   "GO Bond Funding": "$1,700,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,700,000",
   "Project Folder": "https://drive.google.com/drive/folders/0B7OOZhzd-WP1RFZpX0JZZzdOcUE?usp=sharing",
   "Project Webpage (more information)": "http://www.ashevillenc.gov/departments/comm_public/projects_n_initiatives/montford_center_complex_master_plan.htm",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160002.png",
   "Map Tab": "Bond - Parks",
   "Project Updates": "Schematic Designs by Site Design Studio",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 18 - Winter 18",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160031",
   "MUNIS Project Number": "",
   "Project": "Richmond Hill Park Improvements",
   "Display Name": "Richmond Hill Park",
   "Location Details": "280 Richmond Hill Dr",
   "Zip Code": "28806",
   "Category": "Bond - Parks Program",
   "COA Contact": "Allison Dains",
   "Phone Number": "(828) 259-5800",
   "Email Address": "adains@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "Richmond Hill Park is a multi-use park resource in West Asheville.  The City has developed an 18-hole disc golf course and approximately 3.5 miles of mountain biking and hiking trails with volunteer efforts in addition to the parking lot that currently exists on site.  This project will provide supporting amenities to the park such as a restroom facility, a shelter and play areas for youth, as well as enhancing site furnishings such as interpretive signage and maps to enhance the recreational experience for the citizens of Asheville at Richmond Hill Park.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$520,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$520,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160031.jpg",
   "Map Tab": "Bond - Parks",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 19 - Summer 19",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160032",
   "MUNIS Project Number": "",
   "Project": "Ball Field Improvements & Lighting",
   "Display Name": "Ball Fields & Lighting",
   "Location Details": "Citywide",
   "Zip Code": "Citywide",
   "Category": "Bond - Parks Program",
   "COA Contact": "Allison Dains",
   "Phone Number": "(828) 259-5800",
   "Email Address": "adains@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "Ballfield Improvements\nUpgrades and improvements to ballfields are budgeted within the $17 million Parks & Recreation General Obligation bond package. The primary goal of the project is to address maintenance backlog for ballfields while building for the future. Ballfield projects have been prioritized focusing on underserved areas of the city. Each project will address the needs of diverse park users to better reflect changing neighborhoods and their long-term recreation requirements. The ballfields will be designed to utilize ideas and trends from some of the best ballfields in the country, and create enhanced play experience for all users. Ballfield upgrades may include equipment, surfacing, landscaping, dugouts, shade structures, accessible pedestrian systems and other Park & Recreation standard ballfield furnishings.   \n\nPreliminary ballfield sites include:                                                                                                                                                   Ray L. Kisiah Park\nVance Ballfield",
   "Status": "Status: Design",
   "GO Bond Funding": "$1,200,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,200,000",
   "Project Folder": "https://drive.google.com/drive/folders/0B7OOZhzd-WP1Uk1hcDRQQzRPYjA?usp=sharing",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160032.png",
   "Map Tab": "Bond - Parks",
   "Project Updates": "Selected Firm. Negoriating with McGill",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 18 - Winter 19",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160033",
   "MUNIS Project Number": "X1706",
   "Project": "Jake Rusher Park",
   "Display Name": "Jake Rusher Park",
   "Location Details": "132 Peachtree St, Arden, NC 28704",
   "Zip Code": "28704",
   "Category": "Bond - Parks Program",
   "COA Contact": "Dee Black",
   "Phone Number": "(828) 259-5800",
   "Email Address": "dblack@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "Upgrades and improvements to Jake Rusher Park are budgeted within the $17 million Parks & Recreation General Obligation bond package. The completed park will be based on community preferences identified during public input meetings held in April 2016. Overall goals of the project include recognizing the unique history of the community and the park setting as an open space gateway to the neighborhood, borrowing ideas from some of the best neighborhood parks in the country, and aiming to get the biggest bang for the buck while keeping within the project budget.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$825,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$470,566",
   "Total Project Funding (Budget Document)": "$1,295,566",
   "Project Folder": "https://drive.google.com/drive/folders/0B8EPhSQnwfi8VkRSdWVGaGFTSlU?usp=sharing",
   "Project Webpage (more information)": "http://www.ashevillenc.gov/departments/comm_public/projects_n_initiatives/jake_rusher_park.htm",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160033.jpg",
   "Map Tab": "Bond - Parks",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Fall 18 - Summer 19",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160034",
   "MUNIS Project Number": "",
   "Project": "Memorial Stadium",
   "Display Name": "Memorial Stadium",
   "Location Details": "32 Buchanan Place, Asheville, NC 28801",
   "Zip Code": "28801",
   "Category": "Bond - Parks Program",
   "COA Contact": "Christy Bass",
   "Phone Number": "(828) 259-5800",
   "Email Address": "cbass@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "Upgrades and improvements to Memorial Stadium and Mountainside Park are budgeted within the $17 million Parks & Recreation General Obligation bond package. Proposed improvements to stadium and park would increase quality recreation opportunities for the entire community including improved parking, facility access, competition level track and athletic field facilities, sport courts, playground, greenway connections, and restrooms. Facilities will be designed to utilize ideas and trends from some of the best sports fields, sport courts and playgrounds in the country, and create enhanced, inclusive play experience for users of all ages and abilities.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$4,075,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$4,075,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160034.jpg",
   "Map Tab": "Bond - Parks",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 20 - Summer 22",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160035",
   "MUNIS Project Number": "",
   "Project": "Dr. Wesley Grant  Sr. Southside Center Phase 2",
   "Display Name": "Dr. Wesley Grant  Sr. Center Phase 2",
   "Location Details": "285 Livingston Street, Asheville, NC, 28801",
   "Zip Code": "28801",
   "Category": "Bond - Parks Program",
   "COA Contact": "Sandra Travis",
   "Phone Number": "(828) 259-5800",
   "Email Address": "stravis@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "The next phase of the Center development will addresses community identified needs for indoor and outdoor recreation programming and facilities, including a new gym and program space. The primary goal of the project is to build out additional facilities as outlined in the center’s master plan, putting resources in place and keeping equity in mind for adjacent underserved communities.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$4,650,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$4,650,000",
   "Project Folder": "",
   "Project Webpage (more information)": "http://www.ashevillenc.gov/departments/comm_public/projects_n_initiatives/southside_engagement_opportunities.htm",
   "Photo URL": "http://arcgis.ashevillenc.gov/b160035.jpg",
   "Map Tab": "Bond - Parks",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 20 - Summer 22",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160036",
   "MUNIS Project Number": "",
   "Project": "Affordable Housing Feasibility",
   "Display Name": "Affordable Housing Feasibility",
   "Location Details": "1) 171-179 S. Charlotte Street \n(2) 81-91 Riverside Drive \n(3) 319 Biltmore Avenue\n",
   "Zip Code": "28801",
   "Category": "Bond - Housing Program",
   "COA Contact": "Nikki Reid",
   "Phone Number": "(828) 259-5729",
   "Email Address": "nreid@ashevillenc.gov",
   "Owner Department": "Community & Economic Development",
   "Administering Department": "General Services",
   "Project Description": "At the February 7, 2017 City Council Work Session, Council directed staff to proceed with due diligence on three specific City-owned properties to support affordable housing:\n(1) 171-179 S. Charlotte Street \n(2) 81-91 Riverside Drive \n(3) 319 Biltmore Avenue\n",
   "Status": "Status: Planning",
   "GO Bond Funding": "$15,000,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$15,000,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://www.ashevillenc.gov/images/departments/comm_public_engage/projects/Bond/Logos/Word_RED_pms1797_72dpi.png",
   "Map Tab": "Bond - Housing",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "no"
 },
 {
   "GIS_ID": "B160037",
   "MUNIS Project Number": "",
   "Project": "Affordable Housing On City-Owned Property",
   "Display Name": "Affordable Housing Investments",
   "Location Details": "Citywide",
   "Zip Code": "Citywide",
   "Category": "Bond - Housing Program",
   "COA Contact": "Heather Dillashaw",
   "Phone Number": "(828) 259-5851",
   "Email Address": "hdillashaw@ashevillenc.gov",
   "Owner Department": "Community & Economic Development",
   "Administering Department": "Economic Development",
   "Project Description": "Additional support for the Housing Trust Fund and other programs that assist in creating diverse and affordable housing choices.",
   "Status": "Ongoing",
   "GO Bond Funding": "$10,000,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$10,000,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160037.png",
   "Map Tab": "Bond - Housing",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "no"
 },
 {
   "GIS_ID": "B160001",
   "MUNIS Project Number": "X1703",
   "Project": "Bond Bus Shelters",
   "Display Name": "Bond Bus Shelters",
   "Location Details": "",
   "Zip Code": "Citywide",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Dewayne Riddle",
   "Phone Number": "(828) 232-4595",
   "Email Address": "driddle@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of bus shelters, concrete pads, ADA landing areas, sidewalk and wheelchair ramps at various locations.",
   "Status": "Status: Construction",
   "GO Bond Funding": "$500,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$500,000",
   "Project Folder": "https://drive.google.com/drive/folders/0B8EPhSQnwfi8eU5oWDhyRHFKS1k?usp=sharing",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160001.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Bids opened on July 13th to determine contract for construction phase of first set of shelters. Putting together contract with Allison Construction. Reviewing list of bus shelter locations and working on getting easements.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 17 - Fall 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160003",
   "MUNIS Project Number": "X1702",
   "Project": "Bond Traffic Calming",
   "Display Name": "BondTraffic Calming ",
   "Location Details": "Locations TBD",
   "Zip Code": "Citywide",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Chad Bandy",
   "Phone Number": "(828) 259-5431",
   "Email Address": "cbandy@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of speed humps and associated pavement markings. at various locations.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$400,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$400,000",
   "Project Folder": "https://drive.google.com/drive/folders/0B8EPhSQnwfi8UVVnXzdWT1lESG8?usp=sharing",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160003.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Transportation working on petitions. ",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Fall 17 - Spring 18",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160026",
   "MUNIS Project Number": "X1704",
   "Project": "Bond Traffic Signals",
   "Display Name": "Bond Traffic Signals",
   "Location Details": "Patton at N/S French Broad,Patton and Asheland,Patton at Otis,Patton at Lexington ",
   "Zip Code": "28801",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Robert Kun",
   "Phone Number": "(828) 271-6147",
   "Email Address": "rkun@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of new metal mast arm signal poles, traffic signal heads, pedestrian signal crossings and repair/replacement of sidewalk and wheelchair ramps at various intersections along Patton Avenue. Intersections include N/S French Broad Avenue, Otis Street, Asheland Avenue, and N/S Lexington Avenue. ",
   "Status": "Status: Design",
   "GO Bond Funding": "$750,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$750,000",
   "Project Folder": "https://drive.google.com/drive/folders/0B8EPhSQnwfi8ZVFiakpXOFNxdjA?usp=sharing",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/b160026.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Have design plans for replacement of signal poles. ",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Fall 17 - Winter 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160022",
   "MUNIS Project Number": "",
   "Project": "Bond Accessible Crossings",
   "Display Name": "Ped Accessible Crossing",
   "Location Details": "Patton at Florida, Sweeten Cr Rd",
   "Zip Code": "28806",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Chad Bandy",
   "Phone Number": "(828) 259-5431",
   "Email Address": "cbandy@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of pedestrian crossing signals at various intersections, including Patton Avenue at Florida Avenue and Sweeten Creek Road at Doctors Drive. ",
   "Status": "Status: Planning",
   "GO Bond Funding": "$125,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$125,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160022.png",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160125",
   "MUNIS Project Number": "",
   "Project": "Airport Rd Sidewalk",
   "Display Name": "Airport  Rd Sidewalk",
   "Location Details": "US 25 Hendersonville road to the southernmost entrance to Wal-mart",
   "Zip Code": "28704",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Dewayne Riddle",
   "Phone Number": "(828) 232-4595",
   "Email Address": "driddle@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of sidewalk, pedestrian signal crossings, wheelchair ramps, and drainage along NC 280 Airport road from US 25 Hendersonville road to the southernmost entrance to Wal-mart. ",
   "Status": "Status: Design",
   "GO Bond Funding": "$572,500",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$572,500",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/b160125.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected Vauhgn and Melton for Bundle A and Mattern and Craig for Bundle B to begin the design phase. Negotiating professional service contracts.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 18 - Spring 19",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160126",
   "MUNIS Project Number": "",
   "Project": "Johnston Blvd Sidewalk",
   "Display Name": "Johnston Blvd Sidewalk",
   "Location Details": "Patton Ave. to Iona Circle",
   "Zip Code": "28806",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Vincent Sullivan",
   "Phone Number": "(828) 259-5651",
   "Email Address": "vsullivan@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of sidewalk, wheelchair ramps, and drainage along Johnston Blvd from US 19/23 Patton Ave. to Iona Circle.",
   "Status": "Status: Design",
   "GO Bond Funding": "$1,434,500",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,434,500",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160125.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected Vauhgn and Melton for Bundle A and Mattern and Craig for Bundle B to begin the design phase. Negotiating professional service contracts.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 19 - Summer 20",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160127",
   "MUNIS Project Number": "",
   "Project": "Swannanoa River Rd Sidewalk",
   "Display Name": "Swannanoa River Rd Sidewalk",
   "Location Details": "S. Tunnel Rd to Bleachery Blvd",
   "Zip Code": "28805",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Vincent Sullivan",
   "Phone Number": "(828) 259-5651",
   "Email Address": "vsullivan@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of sidewalk, wheelchair ramps, and drainage along US 81 Swannanoa River Rd from S. Tunnel Rd to Bleachery Blvd. ",
   "Status": "Status: Design",
   "GO Bond Funding": "$756,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$756,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160127.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected Vauhgn and Melton for Bundle A and Mattern and Craig for Bundle B to begin the design phase. Negotiating professional service contracts.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 19 - Summer 20",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160005",
   "MUNIS Project Number": "",
   "Project": "Hill Street Sidewalk",
   "Display Name": "Hill Street Sidewalk",
   "Location Details": "Courtland Ave to Riverside Dr",
   "Zip Code": "28801",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Dewayne Riddle",
   "Phone Number": "(828) 232-4595",
   "Email Address": "driddle@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of sidewalk, wheelchair ramps, and drainage along Hill St. from Courtland Ave to Riverside Dr.",
   "Status": "Status: Design",
   "GO Bond Funding": "$468,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$468,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160005.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected Vauhgn and Melton for Bundle A and Mattern and Craig for Bundle B to begin the design phase. Negotiating professional service contracts.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 18 - Summer 18",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160006",
   "MUNIS Project Number": "",
   "Project": " Mills Gap Sidewalk",
   "Display Name": "Mills Gap Sidewalk",
   "Location Details": "US 25 Hendersonville Rd. to US 25 A Sweeten Cr. Rd",
   "Zip Code": "28803",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Robert Kun",
   "Phone Number": "(828) 271-6147",
   "Email Address": "rkun@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of sidewalk, wheelchair ramps, and drainage along Mills Gap Rd. from US 25 Hendersonville Rd. to US 25 A Sweeten Cr. Rd.",
   "Status": "Status: Design",
   "GO Bond Funding": "$128,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$128,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160006.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected Vauhgn and Melton for Bundle A and Mattern and Craig for Bundle B to begin the design phase. Negotiating professional service contracts.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 20 - Summer 21",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160007",
   "MUNIS Project Number": "",
   "Project": "Gerber Rd Sidewalk",
   "Display Name": "Gerber Rd Sidewalk",
   "Location Details": "US 25 Hendersonville Rd. to US 25 A Sweeten Cr. Rd",
   "Zip Code": "28803",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Robert Kun",
   "Phone Number": "(828) 271-6147",
   "Email Address": "rkun@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of sidewalk, wheelchair ramps, and drainage along Gerber Rd. from US 25 Hendersonville Rd. to US 25 A Sweeten Cr. Rd.",
   "Status": "Status: Design",
   "GO Bond Funding": "$357,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$357,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160007.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected Vauhgn and Melton for Bundle A and Mattern and Craig for Bundle B to begin the design phase. Negotiating professional service contracts.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 20 - Summer 21",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160008",
   "MUNIS Project Number": "",
   "Project": " New Haw Creek Rd Sidewalk",
   "Display Name": "New Haw Creek Sidewalk",
   "Location Details": "Beverly Rd. to Bell Rd,",
   "Zip Code": "28805",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Vincent Sullivan",
   "Phone Number": "(828) 259-5651",
   "Email Address": "vsullivan@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of sidewalk, wheelchair ramps, and drainage along New Haw Cr. Rd. from Beverly Rd. to Bell Rd.",
   "Status": "Status: Design",
   "GO Bond Funding": "$1,120,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,120,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160008.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected Vauhgn and Melton for Bundle A and Mattern and Craig for Bundle B to begin the design phase. Negotiating professional service contracts.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 19 - Summer 20",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160009",
   "MUNIS Project Number": "",
   "Project": "Onteora Rd Sidewalk",
   "Display Name": "Onteora Rd Sidewalk",
   "Location Details": "Lincoln Ave. to Raleigh Rd",
   "Zip Code": "28803",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Vincent Sullivan",
   "Phone Number": "(828) 259-5651",
   "Email Address": "vsullivan@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of sidewalk, wheelchair ramps, and drainage along Onteora Blvd. from Lincoln Ave. to Raleigh Rd.",
   "Status": "Status: Design",
   "GO Bond Funding": "$588,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$588,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160009.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected Vauhgn and Melton for Bundle A and Mattern and Craig for Bundle B to begin the design phase. Negotiating professional service contracts.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 19 - Summer 20",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160010",
   "MUNIS Project Number": "",
   "Project": " Overlook Rd Sidewalk",
   "Display Name": "Overlook Rd SIdewalk",
   "Location Details": "Springside Dr. to Briarcliff Dr",
   "Zip Code": "28803",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Dewayne Riddle",
   "Phone Number": "(828) 232-4595",
   "Email Address": "driddle@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of sidewalk, wheelchair ramps, and drainage along Overlook Rd. from Springside Dr. to Briarcliff Dr.",
   "Status": "Status: Design",
   "GO Bond Funding": "$213,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$213,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160010.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected Vauhgn and Melton for Bundle A and Mattern and Craig for Bundle B to begin the design phase. Negotiating professional service contracts.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 19 - Summer 20",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160011",
   "MUNIS Project Number": "",
   "Project": "Brooklyn Rd Improvements",
   "Display Name": "Brooklyn Rd Improvements",
   "Location Details": "Taft Ave. to Shiloh Rd",
   "Zip Code": "28803",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Dewayne Riddle",
   "Phone Number": "(828) 232-4595",
   "Email Address": "driddle@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of new sidewalk and wheelchair ramps along Brooklyn Ave from West Chapel Rd. to Shiloh Rd., sidewalk rehabilitation from Taft Ave. to Shiloh Rd. and resurfacing from Taft Ave. to West Chapel Rd. ",
   "Status": "Status: Planning",
   "GO Bond Funding": "$940,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$940,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160011.png",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 19 - Summer 20",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160012",
   "MUNIS Project Number": "",
   "Project": "Swannanoa River Greenway Phase 1",
   "Display Name": "Swannanoa River Greenway Phase 1",
   "Location Details": "Swannanoa River Greenway",
   "Zip Code": "28803",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Lucy Crown",
   "Phone Number": "(828) 259-5805",
   "Email Address": "lcrown@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Construction of a new greenway south of the Swannanoa River. The greenway project area will begin at South Tunnel Rd and connect to the Asheville Recreation Park. ",
   "Status": "Status: Planning",
   "GO Bond Funding": "$3,600,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$3,600,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160012.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Transportation working on edits for RFQ. ",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 19 - Spring 21",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160013",
   "MUNIS Project Number": "",
   "Project": "Greenway Neighborhood Connectors",
   "Display Name": "Greenway Neighborhood Connectors",
   "Location Details": "Greenway Neighborhood Connectors",
   "Zip Code": "Citywide",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Lucy Crown",
   "Phone Number": "(828) 259-5805",
   "Email Address": "lcrown@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Improvements that provide additonal connections to the city's greenways system. Locations are to be determined. ",
   "Status": "Status: Planning",
   "GO Bond Funding": "$1,000,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,000,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/b160013.png",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 19 - Spring 21",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160014",
   "MUNIS Project Number": "",
   "Project": "Patton Ave New Sidewalks",
   "Display Name": "Patton Ave Sidewalks",
   "Location Details": "Louisiana Dr. to Druid Dr.",
   "Zip Code": "28806",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Vincent Sullivan",
   "Phone Number": "(828) 259-5651",
   "Email Address": "vsullivan@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Installation of new and repair of existing sidewalks and wheelchair ramps on the south side of US 19/23 Patton Ave. from Louisiana Dr. to Druid Dr.  ",
   "Status": "Status: Planning",
   "GO Bond Funding": "$616,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$616,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160014.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 21 - Spring 24",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160015",
   "MUNIS Project Number": "X1711",
   "Project": "Bond Road Improvements",
   "Display Name": "Bond Road Improvements",
   "Location Details": "",
   "Zip Code": "Citywide",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Chuck Watson",
   "Phone Number": "(828) 251-4033",
   "Email Address": "cwatson@ashevillenc.gov",
   "Owner Department": "Public Works",
   "Administering Department": "Public Works",
   "Project Description": "Various road and sidewalk improvements throughout the city. ",
   "Status": "Status: Design",
   "GO Bond Funding": "$16,202,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$16,202,000",
   "Project Folder": "",
   "Project Webpage (more information)": "http://www.ashevillenc.gov/civicax/filebank/blobdload.aspx?blobid=27798",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160126.png",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Awarded to French Broad",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Fall 17 - Spring 18",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160018",
   "MUNIS Project Number": "",
   "Project": "Fulton St Improvements",
   "Display Name": "Fulton St Improvements",
   "Location Details": "Fulton St Improvements",
   "Zip Code": "28801",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Chad Bandy",
   "Phone Number": "(828) 259-5431",
   "Email Address": "cbandy@ashevillenc.gov",
   "Owner Department": "Public Works",
   "Administering Department": "Capital Projects",
   "Project Description": "The re-construction of the existing sidewalk along Fulton St.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$252,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$252,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/b160018.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 19 - Spring 20",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160019",
   "MUNIS Project Number": "",
   "Project": "Vermont Ave Improvements",
   "Display Name": "Vermont Ave Improvements",
   "Location Details": "Vermont Ave Improvements",
   "Zip Code": "28806",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Chad Bandy",
   "Phone Number": "(828) 259-5431",
   "Email Address": "cbandy@ashevillenc.gov",
   "Owner Department": "Public Works",
   "Administering Department": "Capital Projects",
   "Project Description": "The re-construction to the sidewalks along one or both sides of Vermont including new sidewalk to extend to the park. ",
   "Status": "Status: Planning",
   "GO Bond Funding": "$748,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$748,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/b160019.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Summer 19 - Fall 20",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "B160020",
   "MUNIS Project Number": "X1709",
   "Project": "Haywood St Improvements",
   "Display Name": "Haywood St Improvements",
   "Location Details": "Haywood St Improvements",
   "Zip Code": "28801",
   "Category": "Bond - Transportation Program",
   "COA Contact": "Robert Kun",
   "Phone Number": "(828) 271-6147",
   "Email Address": "rkun@ashevillenc.gov",
   "Owner Department": "Public Works",
   "Administering Department": "Capital Projects",
   "Project Description": "Construction of sidewalk and roadway improvements to include drainage and sanitary sewer work. This will be accompanied by street amenities such as benches and street trees",
   "Status": "Status: Design",
   "GO Bond Funding": "$815,000",
   "CIP Funding (total)": "",
   "Grant Funding (total)": "",
   "Other Funding": "",
   "Total Project Funding (Budget Document)": "$815,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/B160020.jpg",
   "Map Tab": "Bond - Transportation",
   "Project Updates": "Selected McGill to move forward with design phase. Negotiating a Professional Services contract for design services.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Spring 19 - Fall 20",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0008",
   "MUNIS Project Number": "B1403",
   "Project": "Parks Maintenance Relocation Phase 1",
   "Display Name": "Parks Maintenance Relocation  Phase 1",
   "Location Details": "Parks Maintenance Relocation",
   "Zip Code": "28801",
   "Category": "CIP - Affordable Housing",
   "COA Contact": "Walter Ear",
   "Phone Number": "(828) 251-4053",
   "Email Address": "wear@ashevillenc.gov",
   "Owner Department": "General Services",
   "Administering Department": "General Services",
   "Project Description": "Phase 1 includes the relocation of the Park Maintenance Division from Hilliard Ave to Hunt Hill. This will allow the Hilliard site to be used for Affordable Housing goals. Phase 2 will consolidate Parks Maintenance with the Facilities Maintenance functions at Shelburne Road.",
   "Status": "Status: Completed",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$337,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$337,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0008.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "FY2017 Budget document shows $1,055,000. Project was split into phase 1 and 2. All remaining funds not used on phase 1 will go to phase 2.  Currently $337,000 in phase 1, and $718,000 in phase 2.",
   "LTD Actuals": 299417.99,
   "Bond Spent": 299417.99,
   "Estimated Construction Timeframe": "Completed Spring 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0011",
   "MUNIS Project Number": "",
   "Project": "Eagle Market Place",
   "Display Name": "Eagle Market Place",
   "Location Details": "Eagle Market Place",
   "Zip Code": "28801",
   "Category": "CIP - Affordable Housing",
   "COA Contact": "Heather Dillashaw",
   "Phone Number": "(828) 259-5851",
   "Email Address": "hdillashaw@ashevillenc.gov",
   "Owner Department": "Community & Economic Development",
   "Administering Department": "Community Development",
   "Project Description": "The contribution of City funds to a Mountain Housing Opportunities (MHO) project for the renovation of buildings on Eagle and Market Street. The goal of the project is to stimulate growth in the area by adding commercial space and mixed-income housing.",
   "Status": "",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$3,900,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$3,900,000",
   "Project Folder": "",
   "Project Webpage (more information)": "http://www.mtnhousing.org/eagle-market-place-7/",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0011.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0012",
   "MUNIS Project Number": "F1401",
   "Project": "Fire Station #13",
   "Display Name": "Fire Station 14",
   "Location Details": "Fire Station 14",
   "Zip Code": "28801",
   "Category": "CIP - Public Safety",
   "COA Contact": "Walter Ear",
   "Phone Number": "(828) 251-4053",
   "Email Address": "wear@ashevillenc.gov",
   "Owner Department": "Fire Department",
   "Administering Department": "General Services",
   "Project Description": "The design and construction of a new fire station on Broadway Street. The fire station will primarily serve the Northwest and Central sections of Asheville.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$3,383,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$3,383,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://coablog.ashevillenc.gov/wp-content/uploads/2015/12/AFD-truck.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 529975.89,
   "Bond Spent": 529975.89,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0015",
   "MUNIS Project Number": "K1702",
   "Project": "US-70 Sidewalk Failure",
   "Display Name": "Tunnel Road Retaining Wall",
   "Location Details": "Tunnel Road Retaining Wall",
   "Zip Code": "28805",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Robert Kun",
   "Phone Number": "(828) 271-6147",
   "Email Address": "rkun@ashevillenc.gov",
   "Owner Department": "Public Works",
   "Administering Department": "Capital Projects",
   "Project Description": "The construction of a retaining wall along US-70 to stabilize the sidewalk.",
   "Status": "Status: Completed",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$650,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$650,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0015.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Getting close to the end. When have walk through, will invite DOT.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Completed Summer 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0016",
   "MUNIS Project Number": "T1802",
   "Project": "Greenway Connectors",
   "Display Name": "Greenway Connectors",
   "Location Details": "Greenway Connectors",
   "Zip Code": "28801",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Lucy Crown",
   "Phone Number": "(828) 259-5805",
   "Email Address": "lcrown@ashevillenc.gov",
   "Owner Department": "Transportation ",
   "Administering Department": "Capital Projects",
   "Project Description": "The design and construction of a network of on-street improvements to connect greenways near Asheville's East of the Riverway and South Slope areas. Improvements include wayfinding and infrastructure upgrades to safely guide users between greenways and surrounding destinations.",
   "Status": "Status: Design",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$840,000",
   "Grant Funding (total)": "$1,050,000",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,890,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0016.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Contract with Alta for design phase.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0005",
   "MUNIS Project Number": "K1402",
   "Project": "Cedar Street Bridge Repair",
   "Display Name": "Cedar Street Bridge",
   "Location Details": "Cedar Street Bridge",
   "Zip Code": "28803",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Dewayne Riddle",
   "Phone Number": "(828) 232-4595",
   "Email Address": "driddle@ashevillenc.gov",
   "Owner Department": "Public Works",
   "Administering Department": "Capital Projects",
   "Project Description": "The Cedar Street Bridge Repair project repaired the 122 foot long bridge that carries Cedar Street across the Norfolk Southern Railroad. The current bridge was originally constructed in 1966.",
   "Status": "Status: Construction",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$500,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$500,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0005.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Almost done with construction. Contaminated lead paint that needs to be removed.Sent paperwork for removing them. Want to wait to open to two lanes. Done with railroad flagger, need to get bill (15 days over 45 days in agreement). Need to schedule a walk through and go through punch list.",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Completed Summer 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0009",
   "MUNIS Project Number": "K1611",
   "Project": "Broadway Vaulted Sidewalk",
   "Display Name": "Broadway Vaulted Sidewalk",
   "Location Details": "Tingle Alleyway to the corner of Broadway and Walnut Street",
   "Zip Code": "28801",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Dewayne Riddle",
   "Phone Number": "(828) 232-4595",
   "Email Address": "driddle@ashevillenc.gov",
   "Owner Department": "Public Works",
   "Administering Department": "Capital Projects",
   "Project Description": "The Broadway Vaulted Sidewalk project will rebuild the vaulted sidewalk along Broadway from Walnut Street to Tingle Alley while taking additional measures to increase the safety of the vault underneath.",
   "Status": "Status: Completed",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$250,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$250,000",
   "Project Folder": "Project Folder - Broadway Vaulted Sidewalks",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0009.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Complete",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Completed Summer 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0010",
   "MUNIS Project Number": "Q1531",
   "Project": "Charlotte Street Improvements",
   "Display Name": "Charlotte Street",
   "Location Details": "Charlotte Street",
   "Zip Code": "28801",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Stephanie Monson",
   "Phone Number": "(828) 232-4502",
   "Email Address": "smonson@ashevillenc.gov",
   "Owner Department": "Strategic Development Office",
   "Administering Department": "Capital Projects",
   "Project Description": "The planning and design of improvements in the Charlotte Street Innovation District.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$1,250,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,250,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0010.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Owner Dept is working to create a project charter to define scope of work",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0017",
   "MUNIS Project Number": "K1404",
   "Project": "Hendersonville Rd Sidewalk",
   "Display Name": "Hendersonville Rd Sidewalk",
   "Location Details": "Hendersonville Rd Sidewalk",
   "Zip Code": "28803",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Vincent Sullivan",
   "Phone Number": "(828) 259-5651",
   "Email Address": "vsullivan@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "The Hendersonville Road Sidewalk project provides new sidewalk along the eastern shoulder of Hendersonville Road (US 25). The project will consist of installation of approximately 13,000 linear feet of new concrete sidewalk, construction of new curbing, 11 retaining walls, drainage structure, and pedestrian crossing signal facilities.",
   "Status": "Status: Construction",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$4,163,448",
   "Grant Funding (total)": "",
   "Other Funding": "",
   "Total Project Funding (Budget Document)": "$4,191,429",
   "Project Folder": "",
   "Project Webpage (more information)": "http://www.ashevillenc.gov/departments/comm_public/projects_n_initiatives/hendersonville.htm",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0017.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Have the bid retaining wall going up and a smaller retaining wall. Have a few punch list items to fix as well. Duke is billing ",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": " Target Completion Fall 2017",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0014",
   "MUNIS Project Number": "K1502",
   "Project": "Neighborhood Sidewalks Program ",
   "Display Name": "Neighborhood Sidewalks Program ",
   "Location Details": "Neighborhood Sidewalks Program ",
   "Zip Code": "Citywide",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Robert Kun",
   "Phone Number": "(828) 271-6147",
   "Email Address": "rkun@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Continunous Investment in critical sidewalk linkages throughout the city. The funding for this program is renewed annually. Current project locations include: Majestic Avenue, Mitchell Avenue, and Wood Avenue.",
   "Status": "Status: Design",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$940,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$940,000",
   "Project Folder": "",
   "Project Webpage (more information)": "https://drive.google.com/file/d/0B5y5xB5sGeofM29Sb1RWQlpuQWM/view?ts=598b47ba",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0014.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Mitchell, Majestic, and Wood have designs and ready to have RFP for construction. Have all ROE for Majestic. ",
   "LTD Actuals": 0,
   "Bond Spent": 0,
   "Estimated Construction Timeframe": "Fall 2017 - Summer 18",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0018",
   "MUNIS Project Number": "K1604",
   "Project": "New Leicester Hwy Sidewalks",
   "Display Name": "New Leicester Hwy Sidewalks",
   "Location Details": "Patton Ave to the City Limits",
   "Zip Code": "28806",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Vincent Sullivan",
   "Phone Number": "(828) 259-5651",
   "Email Address": "vsullivan@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "The New Leicester Highway Sidewalks project is a partnership project with the Department of Transportation to add sidewalks and pedestrian crossings on New Leicester Highway (NC81) from Patton Avenue to the City limits.",
   "Status": "Status: Design",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$726,000",
   "Grant Funding (total)": "$2,904,000",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$3,630,000",
   "Project Folder": "Project Folder - New Leicester Hwy",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0018.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Mattern and Craig working on design.",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "Spring 18 - Fall 19",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0023",
   "MUNIS Project Number": "K1606",
   "Project": "Hazel Mill Rd Sidewalk",
   "Display Name": "Hazel Mill Rd Sidewalk",
   "Location Details": "Hazel Mill Rd from Louisiana Ave to Patton Ave",
   "Zip Code": "28806",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Chad Bandy",
   "Phone Number": "(828) 259-5431",
   "Email Address": "cbandy@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "The Hazel Mill Road Sidewalk project will provide pedestrian links to transit from a proposed housing development that includes affordable housing units.",
   "Status": "Status: Design",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$417,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$417,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0023.png",
   "Map Tab": "",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0013",
   "MUNIS Project Number": "Q1701",
   "Project": "River Arts Transportation Improvement Project (RADTIP) - Construction",
   "Display Name": "River Arts Transportation Improvement Project (RADTIP)",
   "Location Details": "",
   "Zip Code": "28801",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Stephanie Monson",
   "Phone Number": "(828) 232-4502",
   "Email Address": "smonson@ashevillenc.gov",
   "Owner Department": "Strategic Development Office",
   "Administering Department": "Capital Projects",
   "Project Description": "The construction of multi-modal transportation improvements in the River Arts Innovation District. Total project budget and expenses represent construction-related activities for this project.",
   "Status": "Status: Construction",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$20,536,484",
   "Grant Funding (total)": "$17,100,000",
   "Other Funding": "$1,046,960",
   "Total Project Funding (Budget Document)": "$38,683,444",
   "Project Folder": "Project Folder - TIGER VI",
   "Project Webpage (more information)": "http://www.ashevillenc.gov/departments/community/strategic_development_office/riverfront/river_news_and_updates.htm",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0013.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Outreach process for multi-use path options. Aug 22nd recommendation to Council of how to phase future phases of the project. August start demolition to offically start construction.  Online polling continuing.  Demo can start soon (have demo permits). ",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "Summer 17 - ",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0003",
   "MUNIS Project Number": "Q1621",
   "Project": "14 Riverside Drive",
   "Display Name": "14 Riverside Drive",
   "Location Details": "14 Riverside Drive",
   "Zip Code": "28801",
   "Category": "CIP - Economic Development",
   "COA Contact": "Stephanie Monson",
   "Phone Number": "(828) 232-4502",
   "Email Address": "smonson@ashevillenc.gov",
   "Owner Department": "Strategic Development Office",
   "Administering Department": "Capital Projects",
   "Project Description": "The 14 Riverside Drive project includes the renovation and civil work for an 1,800 square foot City-owned building and site adjacent to future park and greenway space in the River Arts District.",
   "Status": "Status: Completed",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$516,757",
   "Grant Funding (total)": "$450,000",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$966,757",
   "Project Folder": "",
   "Project Webpage (more information)": "http://www.ashevillenc.gov/departments/community/strategic_development_office/14_riverside_drive.htm",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0003.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Complete",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "Completed Summer 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0006",
   "MUNIS Project Number": "",
   "Project": "Jean Webb Boat Access",
   "Display Name": "Jean Webb Boat Ramp",
   "Location Details": "Edge of Jean Webb Park",
   "Zip Code": "28806",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Stephanie Monson",
   "Phone Number": "(828) 232-4502",
   "Email Address": "smonson@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Parks and Rec Dept.",
   "Project Description": "A partnership with the NC Wildlife Resources Commission for the addition of a boat ramp on the French Broad River on the edge of Jean Webb Park.",
   "Status": "Status: Construction",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$56,500",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$56,500",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0006.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0022",
   "MUNIS Project Number": "",
   "Project": "I - 26 Connector",
   "Display Name": "I - 26 Connector",
   "Location Details": "I - 26 Connector",
   "Zip Code": "28806",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Transportation Department",
   "Phone Number": "(828) 259-5405",
   "Email Address": "",
   "Owner Department": "Transportation",
   "Administering Department": "Transportation",
   "Project Description": "City contributions to a partnership with the North Ccarolina Department of Transportation (NCDOT) for their project that will connect I-26 to US 19/23/70.",
   "Status": "",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$2,000,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$2,000,000",
   "Project Folder": "",
   "Project Webpage (more information)": "https://www.ncdot.gov/projects/I26Connector/",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0022.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "no"
 },
 {
   "GIS_ID": "C0019",
   "MUNIS Project Number": "C1611",
   "Project": "Thomas Wolfe Auditorium Design",
   "Display Name": "Thomas Wolfe Auditorium Design",
   "Location Details": "Thomas Wolfe ",
   "Zip Code": "28801",
   "Category": "CIP - General Government",
   "COA Contact": "Chris Corl",
   "Phone Number": "(828) 259-5452",
   "Email Address": "ccorl@ashevillenc.gov",
   "Owner Department": "Community & Economic Development",
   "Administering Department": "General Services",
   "Project Description": "Phase 1 design for improvements to the Thomas Wolfe Auditorium that includes updates to patron technology, client needs, and public safety. ",
   "Status": "Status: Design",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$580,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$580,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0019.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0027",
   "MUNIS Project Number": "C1701",
   "Project": "USCC Concert Equipment and HVAC",
   "Display Name": "USCC Curtaining and HVAC",
   "Location Details": "USCC Curtaining and HVAC",
   "Zip Code": "28801",
   "Category": "CIP - General Government",
   "COA Contact": "Chris Corl",
   "Phone Number": "(828) 259-5452",
   "Email Address": "ccorl@ashevillenc.gov",
   "Owner Department": "Community & Economic Development",
   "Administering Department": "General Services",
   "Project Description": "Upgrades to the cutaining and HVAC at the U.S. Cellular Center. Improvements also include concert quality sound, light & rigging equipment, additional meeting and storage space.",
   "Status": "Status: Design",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$1,790,600",
   "Grant Funding (total)": "$1,500,000",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$3,290,600",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0027.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "Spring 18 - Fall 18",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0001",
   "MUNIS Project Number": "R1601",
   "Project": "Swimming Pools",
   "Display Name": "Swimming Pools",
   "Location Details": "Walton Street",
   "Zip Code": "28801",
   "Category": "CIP - Parks & Recreation",
   "COA Contact": "Sandra Travis",
   "Phone Number": "(828) 259-5800",
   "Email Address": "stravis@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "The swimming pools project will address safety and maintenance concerns at City pools.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$2,085,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$2,085,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://static-39.sinclairstoryline.com/resources/media/242a814d-162c-457b-8550-7c154507e4c7-large16x9_05.27pool2.jpg?1464381595857",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "Summer 20 - Summer 22",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0002",
   "MUNIS Project Number": "R1405",
   "Project": "Velodrome Resurfacing",
   "Display Name": "Velodrome Safety",
   "Location Details": "Carrier Park",
   "Zip Code": "28806",
   "Category": "CIP - Parks & Recreation",
   "COA Contact": "Sandra Travis",
   "Phone Number": "(828) 259-5800",
   "Email Address": "stravis@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Capital Projects",
   "Project Description": "The Velodrome Safety project will rebuild the velodrome to address safety issues in the pavement and lighting.",
   "Status": "Status: Construction",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$1,420,777",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$1,420,777",
   "Project Folder": "",
   "Project Webpage (more information)": "http://www.ashevillenc.gov/departments/parks/inventory/carrier_park_improvements.htm",
   "Photo URL": "https://arcgis.ashevillenc.gov/c0002.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": " In construction. Finish end of October",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "Summer 17 - Fall 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0007",
   "MUNIS Project Number": "",
   "Project": "Carrier Park Improvements",
   "Display Name": "Carrier Park Improvements",
   "Location Details": "Carrier Park Improvements",
   "Zip Code": "28806",
   "Category": "CIP - Parks & Recreation",
   "COA Contact": "Parks & Rec Department",
   "Phone Number": "(828) 259-5800",
   "Email Address": "",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Parks and Rec Dept.",
   "Project Description": "Phase 2 of the Carrier Park Improvements includes the design and construction of the covered player seating at the inline rink and roof/siding improvements to the multi-purpose building.",
   "Status": "Status: Design",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$677,550",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$677,550",
   "Project Folder": "",
   "Project Webpage (more information)": "http://www.ashevillenc.gov/departments/parks/inventory/carrier_park_improvements.htm",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0007.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0020",
   "MUNIS Project Number": "R1201",
   "Project": "Beaucatcher Greenway ",
   "Display Name": "Beaucatcher Greenway ",
   "Location Details": "Beaucatcher Greenway ",
   "Zip Code": "28801",
   "Category": "CIP - Parks & Recreation",
   "COA Contact": "Lucy Crown",
   "Phone Number": "(828) 259-5805",
   "Email Address": "lcrown@ashevillenc.gov",
   "Owner Department": "Transportation",
   "Administering Department": "Capital Projects",
   "Project Description": "Construction of a new greenway along Beaucatcher Mountain south of downtown. The greenway will connect from Memorial Stadium to Helen's Bridge located on the northern ridge of Beaucatcher Mountain. ",
   "Status": "Status: Planning",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$2,201,264",
   "Grant Funding (total)": "$975,000",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$3,176,264",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0020.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0025",
   "MUNIS Project Number": "",
   "Project": "John Lewis Turf Replacement",
   "Display Name": "John Lewis Turf",
   "Location Details": "JB Lewis Soccer Complex",
   "Zip Code": "28805",
   "Category": "CIP - Parks & Recreation",
   "COA Contact": "Parks & Rec Department",
   "Phone Number": "(828) 259-5800",
   "Email Address": "",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Parks and Rec",
   "Project Description": "The replacement of artificial turf at the JB Lewis Soccer Complex with a crumb rubber infill.",
   "Status": "Status: Construction",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$743,040",
   "Grant Funding (total)": "$1,100,000",
   "Other Funding": "$356,960",
   "Total Project Funding (Budget Document)": "$2,200,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0025.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "Summer 17  - Summer 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0024",
   "MUNIS Project Number": "R1702",
   "Project": "Nature Center Entrance",
   "Display Name": "Nature Center Entrance",
   "Location Details": "Nature Center Entrance",
   "Zip Code": "28805",
   "Category": "CIP - Parks & Recreation",
   "COA Contact": "Chris Gentile",
   "Phone Number": "(828) 259-8090",
   "Email Address": "CGentile@ashevillenc.gov",
   "Owner Department": "Parks & Recreation",
   "Administering Department": "Parks and Rec",
   "Project Description": "The construction of a new entrance for the WNC nature center. Improvements will include ADA handicapped parking and ramp, sidewalks, new restrooms, an events plaza, new educational space and exhibits.",
   "Status": "Status: Construction",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$461,197",
   "Grant Funding (total)": "$0",
   "Other Funding": "$707,000",
   "Total Project Funding (Budget Document)": "$1,168,197",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0024.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "Summer 17  - Fall 17",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0031",
   "MUNIS Project Number": "",
   "Project": "Transportation Bond Contingency",
   "Display Name": "",
   "Location Details": "",
   "Zip Code": "Citywide",
   "Category": "Bond - Transportation Program",
   "COA Contact": "",
   "Phone Number": "",
   "Email Address": "",
   "Owner Department": "",
   "Administering Department": "",
   "Project Description": "",
   "Status": "",
   "GO Bond Funding": "$415,000",
   "CIP Funding (total)": "$0",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$415,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "",
   "Map Tab": "",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "no"
 },
 {
   "GIS_ID": "C0032",
   "MUNIS Project Number": "",
   "Project": "S. Lexington Ave - Feasibility & Design",
   "Display Name": "South Lexington Ave",
   "Location Details": "Patton to Southside",
   "Zip Code": "28801",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Stephanie Monson",
   "Phone Number": "(828) 232-4502",
   "Email Address": "smonson@ashevillenc.gov",
   "Owner Department": "Strategic Development Office",
   "Administering Department": "",
   "Project Description": "",
   "Status": "Status: Planning",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$675,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$675,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0032.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Owner Department working on project charter",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0033",
   "MUNIS Project Number": "",
   "Project": "Coxe Ave - Feasibility & Design",
   "Display Name": "Coxe Ave",
   "Location Details": "Patton to Southside",
   "Zip Code": "28801",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Stephanie Monson",
   "Phone Number": "(828) 232-4502",
   "Email Address": "smonson@ashevillenc.gov",
   "Owner Department": "Strategic Development Office",
   "Administering Department": "",
   "Project Description": "",
   "Status": "Status: Planning",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$525,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$525,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0033.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "Owner Department working on project charter",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0034",
   "MUNIS Project Number": "",
   "Project": "Lee Walker Heights Redevelopment",
   "Display Name": "Lee Walker Heights Redevelopment",
   "Location Details": "Lee Walker Heights",
   "Zip Code": "28801",
   "Category": "CIP - Affordable Housing",
   "COA Contact": "Heather Dillashaw",
   "Phone Number": "(828) 259-5851",
   "Email Address": "hdillashaw@ashevillenc.gov",
   "Owner Department": "Community & Economic Development",
   "Administering Department": "Community and Economic Development",
   "Project Description": "The Lee Walker Heights initative, led by the Asheville Housing Authority, proposes mixed-income redevelopment of Lee Walker Heights. In April 2016, City Council approved an investment of $4.2 milliont for this project.",
   "Status": "",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$4,200,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$4,200,000",
   "Project Folder": "",
   "Project Webpage (more information)": "http://haca.org/index.php/lee-walker-heights-redevelopment-plan-priorities/",
   "Photo URL": "http://arcgis.ashevillenc.gov/c0034.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "no"
 },
 {
   "GIS_ID": "C0035",
   "MUNIS Project Number": "Q1406",
   "Project": "Asheville Art Museum Upgrades",
   "Display Name": "Asheville Art Museum Upgrades",
   "Location Details": "Pack Square",
   "Zip Code": "28801",
   "Category": "CIP - Parks & Recreation",
   "COA Contact": "",
   "Phone Number": "",
   "Email Address": "",
   "Owner Department": "General Services",
   "Administering Department": "",
   "Project Description": "The City's contribution to the reconstruction of the Asheville Art Museum building in downtown Asheville.",
   "Status": "",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$2,000,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$2,000,000",
   "Project Folder": "",
   "Project Webpage (more information)": "http://www.ashevilleart.org/newmuseum/",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0035.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "no"
 },
 {
   "GIS_ID": "C0029",
   "MUNIS Project Number": "",
   "Project": "Chunn's Cove Bridge Repair",
   "Display Name": "Chunn's Cove Bridge",
   "Location Details": "Chunn's Cove Bridge",
   "Zip Code": "28805",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Chad Bandy",
   "Phone Number": "(828) 259-5431",
   "Email Address": "cbandy@ashevillenc.gov",
   "Owner Department": "Public Works",
   "Administering Department": "Capital Projects",
   "Project Description": "The Chunn's Cove Bridge repair project provides structural rehabilitation to a 34 foot bridge. The bridge was originally constructed in 1930 with rehabilitations completed in 1983.",
   "Status": "Status: Planning",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$500,000",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$500,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0029.jpg",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "TBD - TBD",
   "Need PM Fields?": "yes"
 },
 {
   "GIS_ID": "C0030",
   "MUNIS Project Number": "",
   "Project": "NC 191 Sidewalk and Bus Pad",
   "Display Name": "NC 191",
   "Location Details": "Interchange at I-26 and NC 191 (Brevard Rd) and widen and reconstruct I-26 from east of Brevard Rd to east of Pond Rd.",
   "Zip Code": "28806",
   "Category": "CIP - Transportation & Infrastructure",
   "COA Contact": "Transportation Department",
   "Phone Number": "(828) 259-5405",
   "Email Address": "",
   "Owner Department": "Transportation",
   "Administering Department": "Transportation",
   "Project Description": "City contributions to an NC Department of Transportation (NCDOT) project to modify the interchange at I-26 and NC 191 (Brevard Rd) and widen and reconstruct I-26 from east of Brevard Rd to east of Pond Rd. The City's contribution includes covering 40% of costs for the construction of sidewalks along Brevard Rd and 100% of costs for the implementation of four concrete bus pads.",
   "Status": "",
   "GO Bond Funding": "$0",
   "CIP Funding (total)": "$58,218",
   "Grant Funding (total)": "$0",
   "Other Funding": "$0",
   "Total Project Funding (Budget Document)": "$58,218",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "http://arcgis.ashevillenc.gov/C0030.png",
   "Map Tab": "General Capital Improvement Program",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": " - ",
   "Need PM Fields?": "no"
 },
 {
   "GIS_ID": "",
   "MUNIS Project Number": "B1704",
   "Project": "Parks Maintenance Relocation Phase 2",
   "Display Name": "Parks Maintenance Relocation Phase 2",
   "Location Details": "75 Shelburne Rd, Asheville, NC",
   "Zip Code": "28806",
   "Category": "CIP - Affordable Housing",
   "COA Contact": "Walter Ear",
   "Phone Number": "(828) 251-4053",
   "Email Address": "wear@ashevillenc.gov",
   "Owner Department": "General Services",
   "Administering Department": "General Services",
   "Project Description": "This will move Park Maintenance from it's interim site at Hunt Hill to Shelburne Road, currently occupied by Facilities Maintenance Divisio.  This action will consolidate maintenance functions at the Shelburne Site.",
   "Status": "Status: Planning",
   "GO Bond Funding": "",
   "CIP Funding (total)": "$718,000",
   "Grant Funding (total)": "",
   "Other Funding": "",
   "Total Project Funding (Budget Document)": "$718,000",
   "Project Folder": "",
   "Project Webpage (more information)": "",
   "Photo URL": "",
   "Map Tab": "",
   "Project Updates": "",
   "LTD Actuals": 0,
   "Bond Spent": null,
   "Estimated Construction Timeframe": "",
   "Need PM Fields?": ""
 }
];

export const getPhasePieChartData = (projectData, categories) => {
  let numInPlanning = 0;
  let numInDesign = 0;
  let numInConstruction = 0;
  let numCompleted = 0;
  let numOngoing = 0;

  for (let project of projectData) {
    if ((project.Category.startsWith('CIP') && categories.includes('General Capital Improvement Program')) || categories.includes(project.Category)) {
      switch(project.Status) {
        case 'Status: Planning':
          numInPlanning += 1;
          break;
        case 'Status: Design':
          numInDesign += 1;
          break;
        case 'Status: Construction':
          numInConstruction += 1;
          break;
        case 'Status: Completed':
          numCompleted += 1;
          break;
        default:
          numOngoing += 1;
      }
    }
  }

  const pieData = [];
  if (numOngoing > 0) {
    pieData.push({ name: 'Ongoing', value: numOngoing });
  }
  pieData.push({ name: 'Completed', value: numCompleted });
  pieData.push({ name: 'Construction', value: numInConstruction });
  pieData.push({ name: 'Design', value: numInDesign });
  pieData.push({ name: 'Planning', value: numInPlanning });

  return pieData;
}

export const getFundsAllocatedAndExpended = (projectData, categories) => {
  let totalExpended = 0;
  let totalAllocated = 0;

  for (let project of projectData) {
    if ((project.Category.startsWith('CIP') && categories.includes('General Capital Improvement Program')) || categories.includes(project.Category)) {
      totalExpended += project['LTD Actuals'];
      if (project['Total Project Funding (Budget Document)'].trim() !== '') {
        let allocated = project['Total Project Funding (Budget Document)'].indexOf('$') === 0 ? project['Total Project Funding (Budget Document)'].slice(1).split(',').join('') : project['Total Project Funding (Budget Document)'].split(',').join('');
        totalAllocated += parseFloat(allocated);
      }
    }
  }

  return [{allocated: parseInt(totalAllocated), 'Expended funds': parseInt(totalExpended), 'Remaining funds': parseInt(totalAllocated) - parseInt(totalExpended)}];
};

export const filterProjects = (projects, categories) => {
  const filteredProjects = [];
  for (let project of projects) {
    if (project.Category.startsWith('CIP') && categories.includes('General Capital Improvement Program')) {
      filteredProjects.push(project);
    } else if (categories.includes(project.Category)) {
      filteredProjects.push(project);
    }
  }
  return filteredProjects;
}

export const urlCategory = (category) => {
  switch (category) {
    case 'Bond - Transportation Program':
      return 'transportation';
    case 'Bond - Parks Program':
      return 'parks';
    case 'Bond - Housing Program':
      return 'housing';
    case 'General Capital Improvement Program':
      return 'general_cip';
    default:
      return 'Project';
  } 
}

export const shortCategory = (category) => {
  switch (category) {
    case 'Bond - Transportation Program':
      return 'Transportation Bonds';
    case 'Bond - Parks Program':
      return 'Parks Bonds';
    case 'Bond - Housing Program':
      return 'Housing Bonds';
    case 'General Capital Improvement Program':
      return 'General Capital Improvement Program';
    default:
      return 'Project';
  }
};

export const longCategory = (category) => {
  switch (category.toLowerCase()) {
    case 'transportation':
      return 'Bond - Transportation Program';
    case 'parks':
      return 'Bond - Parks Program';
    case 'housing':
      return 'Bond - Housing Program';
    case 'general_cip':
      return 'General Capital Improvement Program';
  }
};