export const spanish = {
  adopted_annual_budget: 'Presupuesto Anual Adoptado',
  back: 'Volver',
  capital_projects: 'Proyectos Capitales',
  data_info: 'Alguna explanaci\xF3n de los datos y las limitaciones de los datos.',
  funding_info: 'proyectos en el plan general de mejora de capital de la ciudad (CIP) son financiados por una combinaci\xF3n de ingresos fiscales generales, deuda municipal, subvenciones externas y sociedades.',
  housing_bond_info: 'Housing Bond projects for housing affordability provide additional support for the Housing Trust Fund and other programs that assist in creating diverse and affordable housing choices. The projects also include support in the development of affordable housing on key City-owned sites.',
  include_only_bond_projects: 'Include only bond projects',
  ongoing_programs: 'Es posible que programas en curso y proyectos de mantenimiento regular no aparezcan en este tablero de control. Para una lista completa de proyectos en curso y de mantenimiento regular en el plan general de mejora de capital de la ciudad, lee el',
  other_category_note: 'Proyectos categorizados como "Otro" apoyan a la modernizaci\xF3n de instalaciones e iniciativas de desarrollo econ\xF3mico.',
  parks_bond_info: 'Parks Bond projects are additional projects that support the completion of major improvements to five parks and recreation facilities; acquiring land for parks; and improving outdoor courts, playgrounds and ball field lighting throughout the city.',
  project_budgets_note: 'Tenga en cuenta: los presupuestos actuales de proyectos incluyen el financiamiento del a\xF1o anterior y puedan cambiar a lo largo de la vida de cada proyecto.',
  understand_the_capital_projects_data: 'Entender los datos de los proyectos capitales',
  search_by_note: 'Se puede hacer b\xFAsquedas por geograf\xEDa o por direcci\xF3n',
  select_a_category: 'Seleccione una categor\xEDa arriba para mostrar datos sobre proyectos',
  spent: 'Gastado',
  total_budget: 'Presupuesto total',
  transportation_bond_info: 'Proyectos del bono del transporte son proyectos adicionals que contribuyen a la finalizaci\xF3n de la repavimentaci\xF3n de carreteras y mejoras de aceras; nuevas proyectos de aceras y caminos verdes; y proyectos de seguridad peatonal como cobertizos de paradas de autob\xFAs, accesibles cruces peatonales, se\xF1ales, y medidas para calmar el tr\xE1fico.',
  try_project_map: 'Probar nuestro mapa de proyectos',
  under_contract: 'Bajo contrato',
  view_cip_plan: 'Ver el plan de mejora de capital de la ciudad (CIP)',
};
