export const english = {
  actual: 'Actual',
  account: 'Account',
  adopted: 'Adopted',
  back: 'Back',
  budget_category: 'Budget Category',
  budget_data_explanation: 'Some explanation of the data and limitations of the data, and some links to more detailed reports',
  budget_section: 'Budget Section',
  change_from: 'Change from',
  click_the_triangles: 'Click the triangles at left to expand rows for more detail',
  department: 'Department',
  download_here: 'download here',
  departments: 'Departments',
  division: 'Division',
  expenditures: 'Expenditures',
  grouping: 'Grouping',
  internal_audit_note: 'The Internal Audit Division was moved from the Finance Department to the Administration Services Department mid-year, so the 2016-17 Adopted Budget numbers for those department do not match the Original Budget numbers in the budget document.',
  loading_message: 'Loading...Thank you for your patience. The full budget data can take several moments to load',
  notes: 'Notes',
  past_year: 'past year',
  proposed: 'Proposed',
  revenue: 'Revenue',
  table_of: 'Table of',
  top: 'Top',
  treemap_of: 'Treemap of',
  treemap_instructions_1: 'In the treemap below, the size and color of the rectangles represent important information about the',
  treemap_instructions_2: 'budget. The size of each rectangle is proportional to the amount of money budgeted for that category. The color of the rectangle shows the change from last year’s budget. Increases are shown in blue, decreases are orange, and white shows no change. The deeper the color, the larger the change. Click a rectangle to see a detailed breakdown for that category, or mouse over it to see the description and total amount.',
  understand_the_budget_data: 'Understand the budget data',
  use: 'Use',
  you_may_explore: 'You may explore the full dataset in the table below, or',
};
