export const english = {
  actual: 'Actual',
  account: 'Account',
  adopted: 'Adopted',
  back: 'Back',
  bar_chart: 'bar chart',
  bar_chart_note: 'Bar chart totals exclude interfund transfers',
  budget: 'Budget',
  budget_category: 'Budget Category',
  budget_data_explanation: 'Some explanation of the data and limitations of the data, and some links to more detailed reports',
  budget_section: 'Budget Section',
  cash_flow_diagram: 'Cash Flow Diagram',
  cash_flow_chart_intro: 'The chart below shows how revenue flows through the City’s key funds to the various departments. The thickness of each flow is proportional to the amount of money represented. Mouse over the rectangles and flows to see actual amounts.',
  cash_flow_chart_title: 'Cash Flow Diagram: Revenue to Expenditures',
  change_from: 'Change from',
  click_the_triangles: 'Click the triangles at left to expand rows for more detail',
  department: 'Department',
  download_here: 'download here',
  departments: 'Departments',
  details: 'Details',
  division: 'Division',
  expenditures: 'Expenditures',
  flow_diagram: 'Flow diagram',
  full_budget_document: 'Full budget document',
  grouping: 'Grouping',
  internal_audit_note: 'The Internal Audit Division was moved from the Finance Department to the Administration Services Department mid-year, so the 2016-17 Adopted Budget numbers for those department do not match the Original Budget numbers in the budget document.',
  loading_message: 'Loading...Thank you for your patience. The full budget data can take several moments to load',
  notes: 'Notes',
  past_year: 'past year',
  proposed: 'Proposed',
  proposed_budget: 'Proposed budget',
  revenue: 'Revenue',
  summary: 'Summary',
  spending_by_department: 'Spanding By Department',
  spending_by_use: 'Spending By Use',
  table_of: 'Table of',
  top: 'Top',
  treemap_of: 'Treemap of',
  treemap_instructions_1: 'In the treemap below, the size and color of the rectangles represent important information about the',
  treemap_instructions_2: 'budget. The size of each rectangle is proportional to the amount of money budgeted for that category. The color of the rectangle shows the change from last year’s budget. Increases are shown in blue, decreases are orange, and white shows no change. The deeper the color, the larger the change. Click a rectangle to see a detailed breakdown for that category, or mouse over it to see the description and total amount.',
  understand_the_budget_data: 'Understand the budget data',
  use: 'Use',
  you_may_explore: 'You may explore the full dataset in the table below, or',
};
