export const spanish = {
  actual: 'Efectivo',
  account: 'Cuenta',
  adopted: 'Adoptado',
  back: 'Volver',
  budget_category: 'Categor\xEDa de presupuesto',
  budget_data_explanation: 'Alguna explicaci\xF3n de los datos y las limitaciones de los datos, y algunos enlaces a informes m\xE1s detallados',
  budget_section: 'Secci\xF3n de presupuesto',
  change_from: 'Cambio desde',
  click_the_triangles: 'Haga clic en los tri\xE1ngulos a la izquierda para expandir las filas y obtener m\xE1s detalles',
  department: 'Departamento',
  departments: 'Departamentos',
  division: 'Divisi\xF3n',
  download_here: 'descargar aqu\xED',
  expenditures: 'Gastos',
  grouping: 'Agrupamiento',
  internal_audit_note: 'En el medio del a\xF1o 2016-17 la Divisi\xF3n de Auditor\xEDa Interna fue movido del Departamento de Finanzas al Departamento de Servicios Administrativos, entonces los n\xFCmeros de estos dos departamentos en el Presupuesto Adoptado del 2016-17 no coinciden con los n\xFAmeros originales en el documento del presupuesto.',
  loading_message: 'Cargando...Gracias por su paciencia. Puede tomar varios minutos para cagar los datos presupuestarios completos',
  notes: 'Notas',
  past_year: 'el a\xF1o pasado',
  proposed: 'Propuesto',
  revenue: 'Ingresos',
  table_of: 'Tabla de',
  top: 'Cima',
  treemap_of: 'Mapa de \xE1rbol de',
  treemap_instructions_1: 'En el mapa de \xE1rbol por abajo, el tama\xF1o y color de los rect\xE1ngulos representan informaci\xF3n importante acerca del',
  treemap_instructions_2: 'presupuesto. El tama\xF1o de cada rect\xE1ngulo es proporcional a la cantidad de dinero presupuestario en esa categor\xEDa. El color de cada rect\xE1angulo muestra el cambio del presupuesto del a\xF1o pasado. Aumentos son azul, decrecimientos son anaranjados. Cuanto m\xE1s intenso es el color, m\xE1s grande es el cambio. Haga clic en un rect\xE1ngulo para ver un desglose detallado de esa categor\xEDa, o pase el mouse sobre un rect\xE1ngulo para ver la descripci\xF3n y cantidad total.',  
  understand_the_budget_data: 'Entender los datos del presupuesto',
  use: 'Uso',
  you_may_explore: 'Se puede explorar el conjunto de datos entero en la tabla por debajo, o',
};
